### PR TITLE
cleanup bpf progs and maps on BPFHandler destruction

### PR DESCRIPTION
**Pull request by dustin-bingham**

### CODE REVIEW

**Comment by dustin-bingham** [comment]
tail call program fds weren't being closed; failing probe attachment fds weren't being closed.

**Comment by jp-signalfx** [comment]
I'm sad we missed the tail call cleanup the first go around :(

good stuff! Thank you for finding and fixing these!
lgtm

**Review by yonch — APPROVED** [review]
sad we missed the tail call cleanup the first go around :(

good stuff! Thank you for finding and fixing these!
lgtm

**Review by jesafar — APPROVED** [review]
Looks solid to me.  Nice catch on closure of the fd for internal errors as well.

**Pull request merged**
